require 'basic'
require 'plugins'
require 'keybindings'
require 'colorschemes'
require 'plugin-config/nvim-tree'
require 'plugin-config/bufferline'
require 'plugin-config/nvim-treesitter'
require 'plugin-config/cmp'
require 'lsp'
require 'telescope'
require 'gitsigns'
require 'indentline'

